import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import useAuth from "../useAuth";

const useClaimPdf = () => {
  const { user } = useAuth();

  const downloadClaim = (claim) => {
    const doc = new jsPDF();
    const generatedBy = user?.name || user?.email || "System";

    // ── HEADER ──────────────────────────────────────────
    doc.setFillColor(29, 78, 216); // brand blue
    doc.rect(0, 0, 210, 32, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("InsuranceFlow", 105, 13, { align: "center" });

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Claim Summary Report", 105, 23, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(
      `Generated On : ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
      14,
      41,
    );
    doc.text(`Generated By : ${generatedBy}`, 145, 41);

    // ── CLAIM INFO ───────────────────────────────────────
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(29, 78, 216);
    doc.text("Claim Details", 14, 53);
    doc.setTextColor(0, 0, 0);

    autoTable(doc, {
      startY: 58,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
        ["Claim Number", claim.claimNumber || "-"],
        ["Policy Number", claim.policyNumber || "-"],
        ["Customer Name", claim.customerName || "-"],
        [
          "Claim Amount",
          claim.claimAmount != null
            ? `Rs. ${Number(claim.claimAmount).toLocaleString("en-IN")}`
            : "-",
        ],
        ["Claim Status", claim.claimStatus || "-"],
        [
          "Incident Date",
          claim.incidentDate
            ? new Date(claim.incidentDate).toLocaleDateString("en-IN")
            : "-",
        ],
        [
          "Date Filed",
          claim.createdDate
            ? new Date(claim.createdDate).toLocaleDateString("en-IN")
            : "-",
        ],
        ["Claim Reason", claim.claimReason || "-"],
        ["Assigned Staff", claim.assignedStaffName || "Unassigned"],
        ["Staff Remarks", claim.staffRemarks || "-"],
        ["Admin Remarks", claim.adminRemarks || "-"],
        [
          "Last Updated",
          claim.updatedDate
            ? new Date(claim.updatedDate).toLocaleDateString("en-IN")
            : "-",
        ],
      ],
      headStyles: {
        fillColor: [29, 78, 216],
        textColor: 255,
        fontStyle: "bold",
        fontSize: 9,
      },
      bodyStyles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [239, 246, 255] },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 50 } },
    });

    // ── FOOTER ───────────────────────────────────────────
    const pageHeight = doc.internal.pageSize.height;
    doc.setDrawColor(200, 200, 200);
    doc.line(10, pageHeight - 16, 200, pageHeight - 16);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(
      "InsuranceFlow - Insurance Policy & Claim Management System",
      105,
      pageHeight - 10,
      { align: "center" },
    );
    doc.text(
      `Confidential document generated on ${new Date().toLocaleString("en-IN")}`,
      105,
      pageHeight - 5,
      { align: "center" },
    );

    doc.save(`Claim_${claim.claimNumber || 'Doc'}.pdf`);
  };

  return { downloadClaim };
};

export default useClaimPdf;
