import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const useCustomerPdf = () => {

  const downloadCustomer = (customer) => {

    const doc = new jsPDF();

    // ===================== HEADER =====================

    doc.setFillColor(25, 118, 210);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("ABC INSURANCE COMPANY", 105, 12, { align: "center" });

    doc.setFontSize(14);
    doc.text("Customer Details Report", 105, 22, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    doc.text(
      `Generated On : ${new Date().toLocaleDateString()}`,
      14,
      38
    );

    doc.text("Generated By : Staff", 145, 38);

    // ===================== CUSTOMER DETAILS =====================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("1. Customer Details", 14, 50);

    autoTable(doc, {
      startY: 55,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
         ["Customer ID", customer.customerId || "-"],
    ["User ID", customer.userId || "-"],
    ["Full Name", customer.fullName || "-"],
    ["Email", customer.email || "-"],
    ["Mobile Number", customer.mobileNumber || "-"],
    ["Date of Birth", customer.dateOfBirth || "-"],
    ["Address", customer.address || "-"],
    ["City", customer.city || "-"],
    ["State", customer.state || "-"],
    ["Pin Code", customer.pinCode || "-"],
    ["Nominee Name", customer.nomineeName || "-"],
    ["Nominee Relation", customer.nomineeRelation || "-"],
    ["Created Date", customer.createdDate || "-"],
  ],
      headStyles: {
        fillColor: [33, 150, 243],
      },
    });

     // ===================== FOOTER =====================

    const pageHeight = doc.internal.pageSize.height;

    doc.setDrawColor(180);
    doc.line(10, pageHeight - 18, 200, pageHeight - 18);

    doc.setFontSize(9);

    doc.text(
      "ABC Insurance Company",
      105,
      pageHeight - 12,
      { align: "center" }
    );

    doc.text(
      "Insurance Policy & Claim Management System",
      105,
      pageHeight - 7,
      { align: "center" }
    );

    doc.save(`Customer_${customer.fullName}.pdf`);
  };

  return {
    downloadCustomer,
  };
};

export default useCustomerPdf;
