import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const useClaimPdf = () => {

  const downloadClaim = (claim) => {

    const doc = new jsPDF();

    // ===================== HEADER =====================

    doc.setFillColor(25, 118, 210);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("ABC INSURANCE COMPANY", 105, 12, { align: "center" });

    doc.setFontSize(14);
    doc.text("Claim Summary Report", 105, 22, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    doc.text(
      `Generated On : ${new Date().toLocaleDateString()}`,
      14,
      38
    );

    doc.text("Generated By : Agent", 145, 38);

    // ===================== CLAIM DETAILS =====================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Claim Details", 14, 50);

    // autoTable(doc, {
    //   startY: 55,
    //   theme: "grid",
    //   head: [["Field", "Value"]],
    //   body: [
    //     ["Claim ID", claim.claimId || "-"],
    //     ["Claim Number", claim.claimNumber || "-"],
    //     ["Policy Number", claim.policyNumber || "-"],
    //     ["Customer Name", claim.customerName || "-"],
    //     ["Claim Type", claim.claimType || "-"],
    //     ["Claim Amount", `₹ ${claim.claimAmount?.toLocaleString() || "-"}`],
    //     ["Approved Amount", `₹ ${claim.approvedAmount?.toLocaleString() || "-"}`],
    //     ["Claim Status", claim.claimStatus || "-"],
    //     ["Claim Reason", claim.claimReason || "-"],
    //     ["Submitted Date", claim.submittedDate || "-"],
    //     ["Last Updated", claim.lastUpdated || "-"],
    //   ],
    //   headStyles: {
    //     fillColor: [33, 150, 243],
    //   },
    // });


    autoTable(doc, {
  startY: 55,
  theme: "grid",
  head: [["Field", "Value"]],
  body: [
    ["Claim ID", claim.claimId],
    ["Claim Number", claim.claimNumber],
    ["Policy Number", claim.policyNumber],
    ["Customer Name", claim.customerName],
    ["Claim Amount", `₹ ${claim.claimAmount?.toLocaleString()}`],
    ["Claim Status", claim.claimStatus],
    ["Incident Date", claim.incidentDate],
    ["Claim Reason", claim.claimReason],
    ["Agent Remarks", claim.agentRemarks],
    ["Admin Remarks", claim.adminRemarks],
    ["Created Date", claim.createdDate],
    ["Last Updated", claim.updatedDate],
  ],
  headStyles: {
    fillColor: [33, 150, 243],
  },
});

    // ===================== FOOTER =====================

    const pageHeight = doc.internal.pageSize.height;

    doc.setDrawColor(180);
    doc.line(10, pageHeight - 18, 200, pageHeight - 18);

    doc.setFontSize(9);

    doc.text(
      "ABC Insurance Company",
      105,
      pageHeight - 12,
      { align: "center" }
    );

    doc.text(
      "Insurance Policy & Claim Management System",
      105,
      pageHeight - 7,
      { align: "center" }
    );

    doc.save(`Claim_${claim.claimNumber}.pdf`);
  };

  return {
    downloadClaim,
  };
};

export default useClaimPdf;