import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const usePolicyPdf = () => {

  const downloadPolicy = (policy) => {

    const doc = new jsPDF();

    // ===================== HEADER =====================

    doc.setFillColor(25, 118, 210);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("ABC INSURANCE COMPANY", 105, 12, { align: "center" });

    doc.setFontSize(14);
    doc.text("Policy Summary Report", 105, 22, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    doc.text(
      `Generated On : ${new Date().toLocaleDateString()}`,
      14,
      38
    );

    doc.text("Generated By : Agent", 145, 38);

    // ===================== POLICY DETAILS =====================

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("1. Policy Details", 14, 50);

    autoTable(doc, {
      startY: 55,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
          ["Policy ID", policy.policyId || "-"],
    ["Policy Number", policy.policyNumber || "-"],
    ["Customer ID", policy.customerId || "-"],
    ["Customer Name", policy.customerName || "-"],
    ["Plan ID", policy.planId || "-"],
    ["Plan Name", policy.planName || "-"],
    ["Product Type", policy.productType || "-"],
    ["Coverage Amount", `₹ ${policy.coverageAmount?.toLocaleString() || "-"}`],
    ["Premium Amount", `₹ ${policy.premiumAmount?.toLocaleString() || "-"}`],
    ["Premium Type", policy.premiumType || "-"],
    ["Total Premium Paid", `₹ ${policy.totalPremiumPaid?.toLocaleString() || "-"}`],
    ["Policy Status", policy.policyStatus || "-"],
    ["Start Date", policy.startDate || "-"],
    ["End Date", policy.endDate || "-"],
    ["Created Date", policy.createdDate || "-"],
  ],
      headStyles: {
        fillColor: [33, 150, 243],
      },
    });

    

    // ===================== FOOTER =====================

    const pageHeight = doc.internal.pageSize.height;

    doc.setDrawColor(180);
    doc.line(10, pageHeight - 18, 200, pageHeight - 18);

    doc.setFontSize(9);

    doc.text(
      "ABC Insurance Company",
      105,
      pageHeight - 12,
      { align: "center" }
    );

    doc.text(
      "Insurance Policy & Claim Management System",
      105,
      pageHeight - 7,
      { align: "center" }
    );

    doc.save(`Policy_${policy.policyNumber}.pdf`);
  };

  return {
    downloadPolicy,
  };
};

export default usePolicyPdf;