import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import useAuth from "../useAuth";

const usePaymentPdf = () => {
  const { user } = useAuth();

  const downloadReceipt = (payment) => {
    const doc = new jsPDF();
    const generatedBy = user?.name || user?.email || "System";

    // ── HEADER ──────────────────────────────────────────
    doc.setFillColor(29, 78, 216);
    doc.rect(0, 0, 210, 32, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("InsuranceFlow", 105, 13, { align: "center" });

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Payment Receipt", 105, 23, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(
      `Generated On : ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
      14,
      41,
    );
    doc.text(`Generated By : ${generatedBy}`, 145, 41);

    // ── PAYMENT DETAILS ───────────────────────────────────
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(29, 78, 216);
    doc.text("Transaction Details", 14, 53);
    doc.setTextColor(0, 0, 0);

    autoTable(doc, {
      startY: 58,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
        ["Transaction Ref", payment.transactionReference || "-"],
        ["Policy Number", payment.policyNumber || "-"],
        ["Plan Name", payment._planName || "-"],
        ["Product Type", payment._productType || "-"],
        [
          "Premium Amount",
          payment.amount != null
            ? `Rs. ${Number(payment.amount).toLocaleString("en-IN")}`
            : "-",
        ],
        ["Payment Mode", payment.paymentMode?.replace('_', ' ') || "-"],
        ["Payment Status", payment.paymentStatus || "-"],
        [
          "Payment Date",
          payment.paymentDate
            ? new Date(payment.paymentDate).toLocaleString("en-IN")
            : "-",
        ],
      ],
      headStyles: {
        fillColor: [29, 78, 216],
        textColor: 255,
        fontStyle: "bold",
        fontSize: 9,
      },
      bodyStyles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [239, 246, 255] },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 65 } },
    });

    // ── FOOTER ───────────────────────────────────────────
    const pageHeight = doc.internal.pageSize.height;
    doc.setDrawColor(200, 200, 200);
    doc.line(10, pageHeight - 16, 200, pageHeight - 16);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(
      "InsuranceFlow - Insurance Policy & Claim Management System",
      105,
      pageHeight - 10,
      { align: "center" },
    );
    doc.text(
      `Confidential document generated on ${new Date().toLocaleString("en-IN")}`,
      105,
      pageHeight - 5,
      { align: "center" },
    );

    doc.save(`Receipt_${payment.transactionReference || 'Doc'}.pdf`);
  };

  return { downloadReceipt };
};

export default usePaymentPdf;
